FROM ruby:2.6.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN apt-get update -qq && \
  apt-get install -y build-essential \
  libpq-dev && \
  gem install bundler

RUN bundle install

COPY . /app
RUN mkdir -p tmp/sockets
RUN mkdir -p tmp/pids

RUN chmod +x /app/production-entrypoint.sh

CMD ["/app/production-entrypoint.sh"]

VOLUME /app/tmp
HEALTHCHECK --interval=10s --timeout=5s --start-period=5s CMD test -e /app/tmp/sockets/puma.sock; exit $status
